// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuYlsY72uUqjJvktb1UQIHk1fM8tfoNME',
    appId: '1:536666037563:web:294532f6475d89b8f32b1e',
    messagingSenderId: '536666037563',
    projectId: 'aptechdbms',
    authDomain: 'aptechdbms.firebaseapp.com',
    storageBucket: 'aptechdbms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD05RTteMcPMUveB9BD94AcfjSGulzd0K8',
    appId: '1:536666037563:android:6fdd07f6077a79cff32b1e',
    messagingSenderId: '536666037563',
    projectId: 'aptechdbms',
    storageBucket: 'aptechdbms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hvwPNRXJf-zsXa9Q76YJCcq8CoHvvYI',
    appId: '1:536666037563:ios:fd93dae96994c2adf32b1e',
    messagingSenderId: '536666037563',
    projectId: 'aptechdbms',
    storageBucket: 'aptechdbms.firebasestorage.app',
    iosBundleId: 'com.example.newtestapp',
  );
}
